name: vybe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  dropdown_button2: ^1.9.2
  flutter_otp_text_field: ^1.1.1
  modal_bottom_sheet: ^2.1.2



  flutter_svg: ^1.1.5
  get: 4.6.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
  uses-material-design: true

